version: '3.8'

networks:
  default:
    name: time-deal

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  mysql:
    image: mysql:8.0.30
    container_name: timedeal-db
    platform: linux/x86_64
    ports:
      - 33306:3306
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timedeal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    restart: always

  mysql-phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: timedeal-db-admin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    platform: linux/x86_64
    restart: always
